In [12]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
import matplotlib.image as img

In [86]:
Name = []
Primary_Type = []
Weight = []
Height = []
HP = []
Experience = []

for x in range(1,252):
    url = "https://pokeapi.co/api/v2/pokemon/" + str(x)
    res = requests.get(url)
    Name.append(res.json()['name'])
    Primary_Type.append(res.json()['types'][0]['type']['name'])
    Weight.append(res.json()['weight'])
    Height.append(res.json()['height'])
    HP.append(res.json()['stats'][0]['base_stat'])
    Experience.append(res.json()['base_experience'])

In [95]:
Poke_Dict = {
    'Pokemon': Name,
    'Type': Primary_Type,
    'Weight': Weight,
    'Height': Height,
    'HP': HP,
    'Experience':Experience
}
Pokemon_DF = pd.DataFrame(Poke_Dict)
Pokemon_DF.index += 1 
Pokemon_DF

        Pokemon     Type  Weight  Height   HP  Experience
1     bulbasaur    grass      69       7   45          64
2       ivysaur    grass     130      10   60         142
3      venusaur    grass    1000      20   80         263
4    charmander     fire      85       6   39          62
5    charmeleon     fire     190      11   58         142
..          ...      ...     ...     ...  ...         ...
248   tyranitar     rock    2020      20  100         300
249       lugia  psychic    2160      52  106         340
250       ho-oh     fire    1990      38  106         340
251      celebi  psychic      50       6  100         300
252     treecko    grass      50       5   40          62

[252 rows x 6 columns]